# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTest
  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.5.1'

  

  platform :ios, '9.0'
  target 'RNTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTest-tvOS

  target 'RNTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
